---
title: Nhs.Portal.Web
timezone: UTC
collections:
  clarifications:
    title: Clarifications
    output: true
    permalink: "/:collection/:name"
    pretty: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: clarifications
  values:
    layout: document
source: dist
gems:
- jekyll-sitemap
- jekyll-seo-tag
