---
title: Офіційний сайт електронної системи охорони здоров’я eHealth
description: Офіційний сайт електронної системи охорони здоров'я eHealth
lang: uk_UA
timezone: UTC
clarificationTypes:
  - "Всім"
  - "Розробникам"
  - "Закладам"
  - "Лікарям"
  - "Пацієнтам"
collections:
  clarifications:
    title: Clarifications
    output: true
    permalink: /:collection/:name/
  providers:
    title: Providers
    output: true
    permalink: /:collection/:name/
  documents:
    output: false
defaults:
- scope:
    path: ''
    type: clarifications
  values:
    layout: document
- scope:
    path: ''
    type: providers
  values:
    layout: provider
source: dist
host: 0.0.0.0
gems:
- jekyll-sitemap
- jekyll-seo-tag
